apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: fe-deploy
spec:
  selector:
    matchLabels:
      app: fe-deploy
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: fe-deploy
    spec:
      containers:
        - name: fe-deploy
          image: frontend
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              hostPort: 3000       
              
# The port that the container is running on in the cluster