apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: fe-service
spec:
  type: LoadBalancer
  selector:
    app: fe-deploy
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
# The port that the container is running on in the cluster