apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: be-service
spec:
  type: ClusterIP # need port forward for this
  # type: NodePort
  # type: Loadbalancer
  clusterIP: 10.104.24.165
  selector:
    app: be-deploy
  ports:
  - port: 8080
    targetPort: 8080
    #NodePort: 30008
    protocol: TCP
# The port that the container is running on in the cluster