apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: fe-deploy
spec:
  selector:
    matchLabels:
      app: fe-deploy
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: fe-deploy
    spec:
      containers:
        - name: fe-deploy
          image: frontend
          # Image that will be used to containers in the cluster
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              hostPort: {{ .Values.service.hostPort }}        
              
# The port that the container is running on in the cluster