apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: fe-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fe-deploy
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
# The port that the container is running on in the cluster