apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: be-service
spec:
  type: {{ .Values.service.type }} # need port forward for this
  # type: NodePort
  # type: Loadbalancer
  clusterIP: {{ .Values.service.ipAddress }}
  selector:
    app: be-deploy
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    #NodePort: 30008
    protocol: TCP
# The port that the container is running on in the cluster